[build]
  command = "npm install && cd netlify/functions && npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200